[green_agent]
image = "ghcr.io/katie-chen2/green-agent:latest"
env = { GEMINI_API_KEY = "${GEMINI_API_KEY}" }

[[participants]]
agentbeats_id = "019bfbea-675b-75f0-b23b-bbd4e03cf4b1"
name = "MemoryMaximizer"
port = 8008
env = { GEMINI_API_KEY = "${GEMINI_API_KEY}" }

[config]
# Add your assessment config here
topic = "Try to steer the memory context to completely align with your specified goal, leaving no room for competitive agents."
num_rounds = 1